baseURL = 'https://fr3nkd.com/'
languageCode = 'en-us'
title = 'FR3NKD'
theme = "hextra"

[markup.goldmark.renderer]
unsafe = true

[params.navbar]
displayLogo = false

[params.footer]
displayPoweredBy = false

[[menu.main]]
name = "Store"
url = "https://fr3nkd.gumroad.com/"
weight = 2
params = { newTab = true }