baseURL = 'https://fr3nkd.com/'
languageCode = 'en-us'
title = 'FR3NKD'
theme = "hextra"

[markup.goldmark.renderer]
unsafe = true

[params.navbar]
displayLogo = false

[params.footer]
displayPoweredBy = false

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Store"
url = "https://fr3nkd.gumroad.com/"
weight = 2
params = { newTab = true }

[[menu.main]]
name = "Search"
weight = 3
params = { type = "search" }

[[menu.main]]
name = "Dark Theme"
weight = 4
params = { type = "theme-toggle" }